name: Build Windows Executable

on:
  push:
    tags:
      - "v*.*.*" # 只在推送 tag（如 v1.0.0）时触发
  workflow_dispatch: # 可手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Release
        run: cargo build --release

      - name: Archive Executable
        run: |
          mkdir dist
          copy target\release\window_switcher.exe dist\
          Compress-Archive -Path dist\* -DestinationPath dist\window_switcher.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/window_switcher.zip

      - name: Upload Release (if tagged)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          files: dist/window_switcher.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
